### ISSUE TITLE
Disabling methods

### ISSUE THREAD

**Issue by josx** [feathersjs-ecosystem/feathers-swagger#63]
Is there any way to disable methods (at least from a custom doc)?

**Comment by jfmmm** [comment]
Need this too, that delete methods for authentification make no sense without a blacklist feature.

**Comment by jfmmm** [comment]
this did the trick #54

**Comment by idealley** [comment]
For normal services if you do not use some methods such as `patch`, `delete`, etc delete them from your class and leave only those that you are actually using. 

If it is a method that you use you can delete it after the doc has been generated:

`delete app.docs.paths['/authentication/{id}'];`

here is a full implementation of a swagger doc for the the authentication service:

```js
  // Adding swagger to the authentication
  app.configure(Object.assign(authentication(config), {
    docs: def
  }));
  
  // if I do not want to show that documentation
  delete app.docs.paths['/authentication/{id}'];
  app.docs.paths['/authentication'].post = Object.assign(
    {}, 
    app.docs.paths['/authentication'].post, def.post);

 // fixing some elements that were not merged
 app.docs.tags[0].description = def.description;
```
`def` is simply a javascript object where I keep my custom documentation for the endpoint.

for a normal service if do the following:

```js
  // Initialize our service with any options it requires
  app.use('/news', Object.assign(createService(options), { docs, id: 'slug' }));
```
This is the only line you need, `docs` is again my custom object, `id`is to modify the id of used in the documentation, so that it showed `slug`
