### ISSUE TITLE
Resolve Errors displayed in Swagger UI

### ISSUE THREAD

**Issue by alinex** [feathersjs-ecosystem/feathers-swagger#91]
After adding the Swagger UI I got a lot of errors:

Resolver error at paths./users.get.responses.200.schema.$ref
Could not resolve reference because of: Could not resolve pointer: /definitions/users list does not exist in document
Resolver error at paths./users.post.parameters.0.schema.$ref
Could not resolve reference because of: Could not resolve pointer: /definitions/users does not exist in document

I am using:

    "@feathersjs/feathers": "^3.0.5",
    "feathers-swagger": "^0.6.0",

How to fix this?

**Comment by ricardovf** [comment]
Also have this problem. Just installed feathers-swagger over the feathers-chat demo app...

"Resolver error at paths./authentication.post.parameters.0.schema.$ref
Could not resolve reference because of: Could not resolve pointer: /definitions/authentication does not exist in document
Resolver error at paths./authentication/{id}.delete.responses.200.schema.$ref
Could not resolve reference because of: Could not resolve pointer: /definitions/authentication does not exist in document
Resolver error at paths./messages.get.responses.200.schema.$ref
Could not resolve reference because of: Could not resolve pointer: /definitions/messages list does not exist in document
Resolver error at paths./messages.post.parameters.0.schema.$ref
Could not resolve reference because of: Could not resolve pointer: /definitions/messages does not exist in document
Resolver error at paths./messages/{_id}.get.responses.200.schema.$ref
Could not resolve reference because of: Could not resolve pointer: /definitions/messages does not exist in document
Resolver error at paths./messages/{_id}.put.parameters.1.schema.$ref
Could not resolve reference because of: Could not resolve pointer: /definitions/messages does not exist in document
Resolver error at paths./messages/{_id}.put.responses.200.schema.$ref
Could not resolve reference because of: Could not resolve pointer: /definitions/messages does not exist in document
Resolver error at paths./messages/{_id}.patch.parameters.1.schema.$ref
Could not resolve reference because of: Could not resolve pointer: /definitions/messages does not exist in document
Resolver error at paths./messages/{_id}.patch.responses.200.schema.$ref
Could not resolve reference because of: Could not resolve pointer: /definitions/messages does not exist in document
Resolver error at paths./messages/{_id}.delete.responses.200.schema.$ref
Could not resolve reference because of: Could not resolve pointer: /definitions/messages does not exist in document
Resolver error at paths./users.get.responses.200.schema.$ref
Could not resolve reference because of: Could not resolve pointer: /definitions/users list does not exist in document
Resolver error at paths./users.post.parameters.0.schema.$ref
Could not resolve reference because of: Could not resolve pointer: /definitions/users does not exist in document
Resolver error at paths./users/{_id}.get.responses.200.schema.$ref
Could not resolve reference because of: Could not resolve pointer: /definitions/users does not exist in document
Resolver error at paths./users/{_id}.put.parameters.1.schema.$ref
Could not resolve reference because of: Could not resolve pointer: /definitions/users does not exist in document
Resolver error at paths./users/{_id}.put.responses.200.schema.$ref
Could not resolve reference because of: Could not resolve pointer: /definitions/users does not exist in document
Resolver error at paths./users/{_id}.patch.parameters.1.schema.$ref
Could not resolve reference because of: Could not resolve pointer: /definitions/users does not exist in document
Resolver error at paths./users/{_id}.patch.responses.200.schema.$ref
Could not resolve reference because of: Could not resolve pointer: /definitions/users does not exist in document
Resolver error at paths./users/{_id}.delete.responses.200.schema.$ref
Could not resolve reference because of: Could not resolve pointer: /definitions/users does not exist in document
Resolver error at paths./organization.get.responses.200.schema.$ref
Could not resolve reference because of: Could not resolve pointer: /definitions/organization list does not exist in document
Resolver error at paths./organization.post.parameters.0.schema.$ref
Could not resolve reference because of: Could not resolve pointer: /definitions/organization does not exist in document
Resolver error at paths./organization/{_id}.get.responses.200.schema.$ref
Could not resolve reference because of: Could not resolve pointer: /definitions/organization does not exist in document
Resolver error at paths./organization/{_id}.put.parameters.1.schema.$ref
Could not resolve reference because of: Could not resolve pointer: /definitions/organization does not exist in document
Resolver error at paths./organization/{_id}.put.responses.200.schema.$ref
Could not resolve reference because of: Could not resolve pointer: /definitions/organization does not exist in document
Resolver error at paths./organization/{_id}.patch.parameters.1.schema.$ref
Could not resolve reference because of: Could not resolve pointer: /definitions/organization does not exist in document
Resolver error at paths./organization/{_id}.patch.responses.200.schema.$ref
Could not resolve reference because of: Could not resolve pointer: /definitions/organization does not exist in document
Resolver error at paths./organization/{_id}.delete.responses.200.schema.$ref
Could not resolve reference because of: Could not resolve pointer: /definitions/organization does not exist in document"

**Comment by alinex** [comment]
It's the same. Hope somebody can help to fix or prevent this error.

**Comment by alinex** [comment]
Icould solve it. I forgot to define the data structure which is stored in the service:

```js
  app.use('/users', createService(options));
```

Has to be changed in:

```js
  // Initialize our service with any options it requires
  const users = createService(options);
  // Describe API for swagger
  users.docs = {
    description: 'Basic service to get the users to be used for accessing this application',
    definitions: {
      'users list': {
        $ref: '#/definitions/users'
      },
      users: {
        "type": "object",
        "required": [ "email", "password" ],
        "properties": {
          "email": {
            "type": "string",
            "description": "Email address as unique identifier"
          },
          "password": {
            "type": "string",
            "description": "Secret password (make it unguessable)"
          },
          "_id": {
            "type": "string",
            "description": "The id of the user"
          }
        }
      }
    }
  };
  // add service
  app.use('/users', users);
```

Also in all other reported services this has to be done.

**Comment by ricardovf** [comment]
@alinex this data structure can be parsed from a mongoose schema?

**Comment by sherrif10** [comment]
-   // Initialize our service with any options it requires
  const users = createService(options);
  // Describe API for swagger
  users.docs = {
    description: 'Basic service to get the users to be used for accessing this application',
    definitions: {
      'users list': {
        $ref: '#/definitions/users'
      },
      users: {
        "type": "object",
        "required": [ "email", "password" ],
        "properties": {
          "email": {
            "type": "string",
            "description": "Email address as unique identifier"
          },
          "password": {
            "type": "string",
            "description": "Secret password (make it unguessable)"
          },
          "_id": {
            "type": "string",
            "description": "The id of the user"
          }
        }
      }
    }
  };
  // add service
  app.use('/users', users);
What do you mean adding such code,, do you added them manually, Also can you indicate for me which class object
